name: "test VS 2022"

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2022

    steps:

    - name: Install checkout
      uses: actions/checkout@v3
    
    - name: Install SHFB
      uses: ./
      with:
        version: 2022.12.30.0
        
    - name: Test
      run: |
           echo SHFBROOT: %SHFBROOT% 
           echo TEMP: %TEMP%
           type %TEMP%\vsixinst.log
      shell: cmd